### ISSUE TITLE
Automated menu query at specified time

### ISSUE THREAD

**Issue by 3dde** [Th3JD/RWTH-LeckerSchmecker#123]
A user suggested a feature: The user can defines a predefined canteen and the bot automatically sends the menu of that canteen at a specific time to the user

This feature could be added as an option that can be enabled (default: off)

**Comment by ekansemit** [comment]
Should the time set by the user or do we only offer a default time like 10 AM?

**Comment by 3dde** [comment]
I thought of providing a setting like the diet type, with some predefined options, for example:

- 9:00
- 10:00
- 11:00
- 12:00
- Off
